#!/usr/bin/env python3
"""
export_c.py -- emit the quantized model and golden test vectors as C headers.

    py/venv/bin/python py/export_c.py --ckpt py/data/model_v3.pt --beats 8

Writes:
    fw/model_data.h   weights, per-channel shifts, activation scales, softplus LUT
    fw/golden.h       N input beats and the exact int32 logits quantize.py produces

The golden vectors are the point. The week-2 gate asks whether the quantized SSM
runs *correctly* on the core, and "correctly" means the C port reproduces
`quantize.py` **bit for bit** -- not that it approximates the float model. So the
expected outputs are exported alongside the inputs and the firmware compares
them itself, on the board, and prints PASS/FAIL. Nothing has to be eyeballed
over UART, and a wrong answer cannot be mistaken for a right one.

Everything float happens here, offline. `np.rint` (round-half-to-even) is used
for bias quantization, which is why the C never needs to reproduce it.
"""

import argparse
import os
import sys

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from model import ECGNet                                   # noqa: E402
import quantize as Q                                       # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.join(os.path.dirname(HERE), "fw")


def carr(f, ctype, name, arr, per_line=16):
    """Emit a flat C array, row-major, with its shape in a comment."""
    a = np.asarray(arr).ravel()
    f.write("/* shape %s */\n" % (tuple(np.asarray(arr).shape),))
    f.write("static const %s %s[%d] = {\n" % (ctype, name, a.size))
    for i in range(0, a.size, per_line):
        f.write("    " + ", ".join("%d" % v for v in a[i:i + per_line]) + ",\n")
    f.write("};\n\n")
    return a.size


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default=os.path.join(HERE, "data", "model_v3.pt"))
    ap.add_argument("--beats", type=int, default=8, help="golden vectors to emit")
    ap.add_argument("--host-beats", type=int, default=0,
                    help="also write py/golden_host.h with this many vectors, for "
                         "the host differential test. Kept separate from fw/golden.h "
                         "because the firmware pays BRAM for every beat it carries "
                         "and 9 is enough to prove the port on hardware; the host "
                         "has no such limit and a wider set is a much stronger check")
    ap.add_argument("--n-cal", type=int, default=600)
    ap.add_argument("--threads", type=int, default=2)
    args = ap.parse_args()
    torch.set_num_threads(args.threads)

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    cfg = ck["config"]
    model = ECGNet(cfg["d_model"], cfg["d_state"], cfg["n_layers"], cfg["n_classes"])
    if "norm_out.weight" in ck["state_dict"]:
        sys.exit("[export] %s carries the reverted final LayerNorm. The C port "
                 "does not implement it; retrain or pick another checkpoint."
                 % os.path.basename(args.ckpt))
    model.load_state_dict(ck["state_dict"])
    model.eval()

    d = np.load(os.path.join(HERE, "data", "beats.npz"))
    Xtr, ytr = d["X_train"], d["y_train"]
    rng = np.random.RandomState(0)
    cal = np.concatenate([
        rng.choice(np.flatnonzero(ytr == c), min(max(1, args.n_cal // 4),
                                                 int((ytr == c).sum())), replace=False)
        for c in np.unique(ytr) if (ytr == c).sum() > 0])
    fa, peak = Q.calibrate(model, Xtr[cal])

    q = Q.QuantECGNet(model, fa)
    D, N, L = cfg["d_model"], cfg["d_state"], cfg["n_layers"]
    NC = cfg["n_classes"]
    T = d["X_train"].shape[1]

    # Golden beats from the DS1 holdout, stratified so the vectors exercise more
    # than the majority class -- a set of pure-N beats would pass even if the
    # scan were badly wrong.
    vm = np.isin(d["rec_train"], Q.VAL_RECORDS)
    Xv, yv = d["X_train"][vm], d["y_train"][vm]
    rng = np.random.RandomState(7)
    per = max(1, args.beats // 3)
    gidx = np.concatenate([rng.choice(np.flatnonzero(yv == c), min(per, int((yv == c).sum())),
                                      replace=False)
                           for c in (0, 1, 2) if (yv == c).sum() > 0])[:args.beats]
    Xg, yg = Xv[gidx], yv[gidx]
    logits = np.asarray(q.forward(Xg), dtype=np.int64)
    assert logits.min() >= -(2**31) and logits.max() < 2**31

    # ---------------------------------------------------------------- model_data.h
    path = os.path.join(FW, "model_data.h")
    with open(path, "w") as f:
        f.write("/* Generated by py/export_c.py -- do not edit.\n"
                " * source: %s   %d params, D=%d N=%d L=%d T=%d\n"
                " */\n#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n"
                "#include <stdint.h>\n\n"
                % (os.path.basename(args.ckpt),
                   sum(p.numel() for p in model.parameters()), D, N, L, T))
        f.write("#define M_D %d\n#define M_N %d\n#define M_L %d\n"
                "#define M_T %d\n#define M_CLASSES %d\n\n" % (D, N, L, T, NC))

        f.write("/* activation scales: fractional bits per site (calibrated) */\n")
        for s in ("res", "norm", "dtp", "dt", "dtx", "bc", "h", "y", "pool", "logit"):
            f.write("#define FA_%-6s %d   /* peak %.3f */\n"
                    % (s.upper(), fa[s], peak[s]))
        f.write("#define FA_A     %d\n" % fa["a"])
        f.write("#define FA_INPUT 15  /* beats.npz is Q15 full-scale */\n\n")

        f.write("/* softplus LUT, %d entries over [%.1f, %.1f] at FA_DTP */\n"
                % (len(q.lut[0]), q.lut[1], q.lut[2]))
        f.write("#define SP_LUT_N %d\n#define SP_LUT_LO %d\n#define SP_LUT_HI %d\n\n"
                % (len(q.lut[0]),
                   int(round(q.lut[1] * (2 ** fa["dtp"]))),
                   int(round(q.lut[2] * (2 ** fa["dtp"])))))
        carr(f, "int32_t", "sp_lut", q.lut[0], 12)

        total = 0
        def w(name, cname, ctype="int8_t"):
            nonlocal total
            qv, s = q.q[name]
            total += carr(f, ctype, cname, qv)
            if s is not None and np.asarray(s).ndim:
                total += carr(f, "int8_t", cname + "_sh", np.asarray(s))
            elif s is not None:
                f.write("#define %s_SH %d\n\n" % (cname.upper(), int(s)))

        def b(name, cname):
            nonlocal total
            bq, _ = q.q[name]
            total += 4 * carr(f, "int32_t", cname, bq, 8)

        w("in_proj.w", "in_proj_w");  b("in_proj.b", "in_proj_b")
        for i in range(L):
            p = "blocks.%d." % i
            w(p + "A", "blk%d_A" % i, "int16_t")
            w(p + "D_skip", "blk%d_dskip" % i)
            for lin in ("dt_proj", "B_proj", "C_proj", "out_proj"):
                w(p + lin + ".w", "blk%d_%s_w" % (i, lin))
                b(p + lin + ".b", "blk%d_%s_b" % (i, lin))
            w("norms.%d.w" % i, "norm%d_w" % i)
            b("norms.%d.b" % i, "norm%d_b" % i)
        w("head.w", "head_w");  b("head.b", "head_b")

        f.write("#endif /* MODEL_DATA_H */\n")
    print("[export] %s  (~%.1f KB of parameter data)" % (path, total / 1024.0))

    # ------------------------------------------------------------------- golden.h
    gpath = os.path.join(FW, "golden.h")
    with open(gpath, "w") as f:
        f.write("/* Generated by py/export_c.py -- do not edit.\n"
                " *\n"
                " * %d beats from the DS1 holdout and the exact int32 logits that\n"
                " * py/quantize.py produces for them. The firmware recomputes these\n"
                " * on the core and compares; anything other than an exact match is\n"
                " * a failure, because both sides are integer arithmetic and there\n"
                " * is no rounding budget to spend.\n"
                " */\n#ifndef GOLDEN_H\n#define GOLDEN_H\n\n#include <stdint.h>\n\n"
                % len(Xg))
        f.write("#define G_BEATS %d\n\n" % len(Xg))
        carr(f, "int16_t", "g_x", Xg, 16)
        carr(f, "int32_t", "g_logits", logits, 8)
        carr(f, "uint8_t", "g_label", yg, 16)
        f.write("#endif /* GOLDEN_H */\n")
    print("[export] %s  (%d beats, labels %s)"
          % (gpath, len(Xg), np.bincount(yg, minlength=5)))

    if args.host_beats:
        rng = np.random.RandomState(11)
        per = max(1, args.host_beats // 3)
        hidx = np.concatenate([rng.choice(np.flatnonzero(yv == c),
                                          min(per, int((yv == c).sum())), replace=False)
                               for c in (0, 1, 2) if (yv == c).sum() > 0])[:args.host_beats]
        Xh, yh = Xv[hidx], yv[hidx]
        lh = np.asarray(q.forward(Xh), dtype=np.int64)
        hp = os.path.join(HERE, "golden_host.h")
        with open(hp, "w") as f:
            f.write("/* Generated by py/export_c.py --host-beats %d. Host test only. */\n"
                    "#ifndef GOLDEN_H\n#define GOLDEN_H\n#include <stdint.h>\n\n"
                    % len(Xh))
            f.write("#define G_BEATS %d\n\n" % len(Xh))
            carr(f, "int16_t", "g_x", Xh, 16)
            carr(f, "int32_t", "g_logits", lh, 8)
            carr(f, "uint8_t", "g_label", yh, 16)
            f.write("#endif\n")
        print("[export] %s  (%d beats, labels %s)"
              % (hp, len(Xh), np.bincount(yh, minlength=5)))

    # A reference dump so the host-side test can check without torch.
    np.savez(os.path.join(HERE, "data", "golden.npz"),
             x=Xg, logits=logits, label=yg, fa=np.array([fa[k] for k in sorted(fa)]),
             fa_keys=np.array(sorted(fa)))
    print("[export] py/data/golden.npz")
    print("[export] predicted classes: %s" % logits.argmax(1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
