#!/bin/bash
# Verilate a7lite_soc_top + CV32E40X core.
# bhv/ and sva/ are assertion-only files Verilator 4.038 cannot parse; the SoC
# instantiates cv32e40x_core directly so they are not needed.
# The FPGA clock gate uses a Xilinx BUFGCE primitive; bhv/cv32e40x_sim_clock_gate.sv
# is the drop-in simulation equivalent (same module name and ports).
# FW_MEM_B* come from ../build/fw_mem_path.svh (generated by scripts/build.tcl).
set -e
cd "$(dirname "$0")"
R=..
grep -v '^\s*//' $R/vendor/cv32e40x/cv32e40x_manifest.flist \
  | sed "s|\${DESIGN_RTL_DIR}|$R/vendor/cv32e40x/rtl|g" \
  | grep -vE '^[[:space:]]*$' | grep -vE '\+incdir' \
  | grep -vE 'bhv/|sva/|assertions' > core.f
echo "RTL files: $(wc -l < core.f)"
/home/ahmedelnour/verilator5/bin/verilator --cc --exe --build -j 8 --MAKEFLAGS OPT_FAST=-O2 -Wno-fatal -Wno-lint -Wno-style \
  --top-module a7lite_soc_top \
  -I$R/vendor/cv32e40x/rtl/include -I$R/build \
  -f core.f \
  $R/rtl/uart_tx.sv $R/vendor/cv32e40x/bhv/cv32e40x_sim_clock_gate.sv $R/rtl/a7lite_soc_top.sv \
  tb_main.cpp -o sim
