# -----------------------------------------------------------------------------
# build.tcl -- non-project synthesis + implementation + bitstream for the
# CV32E40X A7-Lite SoC.
#
#   vivado -mode batch -source scripts/build.tcl
#
# Non-project mode is used deliberately: the whole build is reproducible from
# the repo with no .xpr state to drift out of sync.
#
# The part is selected directly (xc7a35tfgg484-2L). There is no published Vivado
# board file for the A7-Lite, so no board_part is set.
# -----------------------------------------------------------------------------

set root    [file normalize [file join [file dirname [info script]] ..]]
set part    xc7a35tfgg484-2L
set top     a7lite_soc_top
set outdir  $root/build

file mkdir $outdir

# ---------------------------------------------------------------------------
# Generate the firmware path header. $readmemh needs a path that resolves at
# elaboration time; baking an absolute path in here avoids depending on the
# tool's working directory, which differs between synth and simulation.
# ---------------------------------------------------------------------------
set fh [open $outdir/fw_mem_path.svh w]
puts $fh "// Generated by scripts/build.tcl -- do not edit."
for {set lane 0} {$lane < 4} {incr lane} {
  set fw_mem $root/fw/firmware_b$lane.mem
  if {![file exists $fw_mem]} {
    error "$fw_mem not found -- run fw/build.sh first"
  }
  puts $fh "`define FW_MEM_B$lane \"$fw_mem\""
  puts "INFO: byte lane $lane image = $fw_mem"
}
close $fh

# ---------------------------------------------------------------------------
# Sources. The package must be read before the modules that import it.
# bhv/ is intentionally excluded: it holds simulation-only models, including
# cv32e40x_sim_clock_gate.sv, which infers a latch. rtl/cv32e40x_clock_gate.sv
# in this repo is the synthesizable BUFGCE replacement.
# ---------------------------------------------------------------------------
read_verilog -sv $root/vendor/cv32e40x/rtl/include/cv32e40x_pkg.sv
read_verilog -sv [lsort [glob $root/vendor/cv32e40x/rtl/*.sv]]
read_verilog -sv [lsort [glob $root/rtl/*.sv]]
read_xdc $root/constr/a7lite.xdc

# ---------------------------------------------------------------------------
# Synthesis
# ---------------------------------------------------------------------------
synth_design -top $top -part $part \
  -include_dirs [list $outdir $root/vendor/cv32e40x/rtl/include]

write_checkpoint -force $outdir/post_synth.dcp
report_utilization -file $outdir/post_synth_util.rpt

# Latches must not exist in this design: the only latch in the vendor tree is
# the simulation clock gate, so any latch here means the wrong file was picked up.
set latches [get_cells -hier -quiet -filter {PRIMITIVE_SUBGROUP == latch}]
if {[llength $latches] > 0} {
  puts "ERROR: [llength $latches] latch(es) inferred:"
  foreach l $latches { puts "  $l" }
  error "latch inference -- check that bhv/cv32e40x_sim_clock_gate.sv is excluded"
}
puts "INFO: latch check passed (0 latches)"

# ---------------------------------------------------------------------------
# Implementation
# ---------------------------------------------------------------------------
opt_design
place_design
phys_opt_design
route_design

write_checkpoint -force $outdir/post_route.dcp
report_utilization       -file $outdir/post_route_util.rpt
report_timing_summary    -file $outdir/timing_summary.rpt
report_drc               -file $outdir/drc.rpt

# ---------------------------------------------------------------------------
# Timing gate: refuse to emit a bitstream that does not meet timing, so a
# failing build cannot be mistaken for a hardware problem later.
# ---------------------------------------------------------------------------
set wns [get_property SLACK [get_timing_paths -delay_type max]]
set whs [get_property SLACK [get_timing_paths -delay_type min]]
puts "INFO: WNS = $wns ns, WHS = $whs ns"
if {$wns < 0 || $whs < 0} {
  error "TIMING FAILED: WNS=$wns WHS=$whs -- not writing bitstream"
}

write_bitstream -force $outdir/a7lite_soc.bit
puts "INFO: bitstream written to $outdir/a7lite_soc.bit"
