# -----------------------------------------------------------------------------
# create_gui_project.tcl -- regenerate a Vivado project (.xpr) from scratch.
#
# NOT the project to open normally. a7lite_soc/a7lite_soc.xpr is the primary GUI
# project: it is committed, it already references rtl/, constr/, vendor/rtl and
# build/ in place, and it carries the synth/impl run history. This script is the
# rescue path for when that .xpr is corrupted or lost -- it rebuilds an equivalent
# project into vivado_gui/, which is gitignored and disposable.
#
#   vivado -mode batch -source scripts/create_gui_project.tcl
#   then: File -> Open Project -> vivado_gui/a7lite_soc.xpr
#
# The command-line flow (scripts/build.tcl) is non-project mode, which produces no
# .xpr and therefore cannot be opened in the GUI. This script builds an equivalent
# project-mode version: same part, same sources, same constraints, same include
# paths and top module.
#
# Regenerating is safe -- the project directory is deleted and recreated, and
# nothing outside vivado_gui/ is touched. Sources are referenced in place, not
# copied, so edits in the GUI go straight to the repo files.
# -----------------------------------------------------------------------------

set root    [file normalize [file join [file dirname [info script]] ..]]
set part    xc7a35tfgg484-2L
set top     a7lite_soc_top
set projdir $root/vivado_gui
set projnm  a7lite_soc

# ---------------------------------------------------------------------------
# The generated $readmemh header must exist before elaboration. build.tcl
# normally writes it; regenerate here so the GUI project stands alone.
# ---------------------------------------------------------------------------
file mkdir $root/build
set fh [open $root/build/fw_mem_path.svh w]
puts $fh "// Generated by scripts/create_gui_project.tcl -- do not edit."
for {set lane 0} {$lane < 4} {incr lane} {
  set fw_mem $root/fw/firmware_b$lane.mem
  if {![file exists $fw_mem]} {
    error "$fw_mem not found -- run fw/build.sh first"
  }
  puts $fh "`define FW_MEM_B$lane \"$fw_mem\""
}
close $fh

# ---------------------------------------------------------------------------
# Fresh project
# ---------------------------------------------------------------------------
if {[file exists $projdir]} {
  puts "INFO: removing existing $projdir"
  file delete -force $projdir
}
create_project $projnm $projdir -part $part

# Sources are referenced in place so the GUI edits the repo, not a copy.
set_property source_mgmt_mode DisplayOnly [current_project]

# ---------------------------------------------------------------------------
# Design sources. bhv/ is excluded on purpose: it holds the simulation-only
# clock gate that infers a latch.
# ---------------------------------------------------------------------------
set srcs [list $root/vendor/cv32e40x/rtl/include/cv32e40x_pkg.sv]
foreach f [lsort [glob $root/vendor/cv32e40x/rtl/*.sv]] { lappend srcs $f }
foreach f [lsort [glob $root/rtl/*.sv]]                 { lappend srcs $f }

add_files -norecurse -fileset sources_1 $srcs
set_property file_type SystemVerilog [get_files -of [get_filesets sources_1] *.sv]

# Include paths: the package directory, and build/ for fw_mem_path.svh.
set_property include_dirs \
  [list $root/vendor/cv32e40x/rtl/include $root/build] \
  [get_filesets sources_1]

set_property top $top [get_filesets sources_1]

# ---------------------------------------------------------------------------
# Constraints
# ---------------------------------------------------------------------------
add_files -norecurse -fileset constrs_1 $root/constr/a7lite.xdc

update_compile_order -fileset sources_1

puts ""
puts "==================================================================="
puts " Project created."
puts "   open with:  vivado $projdir/$projnm.xpr"
puts "   part:       $part"
puts "   top:        $top"
puts "   sources:    [llength $srcs] files"
puts "==================================================================="
